include_dir=/home/autark/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
sys_include_dir=/home/autark/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android
crt_dir=/home/autark/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/26
msvc_lib_dir=
kernel32_lib_dir=
kernel_header_dir=/home/autark/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
gcc_dir=
